<?xml version="1.0" ?>
<!DOCTYPE datafile [
<!ELEMENT datafile ANY>
	<!ELEMENT header ANY>
		<!ELEMENT emu_name (#PCDATA)>
		<!ELEMENT emu_parser (#PCDATA)>
		<!ELEMENT emu_description (#PCDATA)>
		<!ELEMENT emu_category (#PCDATA)>
		<!ELEMENT emu_version (#PCDATA)>
		<!ELEMENT emu_date (#PCDATA)>
		<!ELEMENT emu_author (#PCDATA)>
		<!ELEMENT emu_homepage (#PCDATA)>
		<!ELEMENT emu_baseurl (#PCDATA)>
		<!ELEMENT emu_launcher (#PCDATA)>
		<!ELEMENT emu_ext_launch_cmd (#PCDATA)>
		<!ELEMENT emu_downloadpath (#PCDATA)>
		<!ELEMENT emu_postdlaction (#PCDATA)>
		<!ELEMENT emu_comment (#PCDATA)>
		<!ELEMENT emu_thumb (#PCDATA)>
		<!ELEMENT emu_banner (#PCDATA)>
		<!ELEMENT emu_fanart (#PCDATA)>
		<!ELEMENT emu_logo (#PCDATA)>
		<!ELEMENT emu_trailer (#PCDATA)>
	<!ELEMENT game ANY>
		<!ATTLIST game name CDATA #REQUIRED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good|verified) "good">
		<!ELEMENT emu_command (#PCDATA)>
		<!ELEMENT title_clean (#PCDATA)>
		<!ELEMENT plot (#PCDATA)>
		<!ELEMENT releasedate (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT genre (#PCDATA)>
		<!ELEMENT studio (#PCDATA)>
		<!ELEMENT nplayers (#PCDATA)>
		<!ELEMENT perspective (#PCDATA)>
		<!ELEMENT rating (#PCDATA)>
		<!ELEMENT ESRB (#PCDATA)>
		<!ELEMENT videoid (#PCDATA)>
		<!ELEMENT thegamesdb_id (#PCDATA)>
		<!ELEMENT gamefaqs_url (#PCDATA)>
		<!ELEMENT moby_url (#PCDATA)>
		<!ELEMENT consolegrid_url (#PCDATA)>
		<!ELEMENT boxart1 (#PCDATA)>
		<!ELEMENT boxart2 (#PCDATA)>
		<!ELEMENT boxart3 (#PCDATA)>
		<!ELEMENT boxart4 (#PCDATA)>
		<!ELEMENT boxart5 (#PCDATA)>
		<!ELEMENT boxart6 (#PCDATA)>
		<!ELEMENT boxart7 (#PCDATA)>
		<!ELEMENT boxart8 (#PCDATA)>
		<!ELEMENT boxart9 (#PCDATA)>
		<!ELEMENT boxart10 (#PCDATA)>
		<!ELEMENT snapshot1 (#PCDATA)>
		<!ELEMENT snapshot2 (#PCDATA)>
		<!ELEMENT snapshot3 (#PCDATA)>
		<!ELEMENT snapshot4 (#PCDATA)>
		<!ELEMENT snapshot5 (#PCDATA)>
		<!ELEMENT snapshot6 (#PCDATA)>
		<!ELEMENT snapshot7 (#PCDATA)>
		<!ELEMENT snapshot8 (#PCDATA)>
		<!ELEMENT snapshot9 (#PCDATA)>
		<!ELEMENT snapshot10 (#PCDATA)>		
		<!ELEMENT fanart1 (#PCDATA)>
		<!ELEMENT fanart2 (#PCDATA)>
		<!ELEMENT fanart3 (#PCDATA)>
		<!ELEMENT fanart4 (#PCDATA)>
		<!ELEMENT fanart5 (#PCDATA)>
		<!ELEMENT fanart6 (#PCDATA)>
		<!ELEMENT fanart7 (#PCDATA)>
		<!ELEMENT fanart8 (#PCDATA)>
		<!ELEMENT fanart9 (#PCDATA)>
		<!ELEMENT fanart10 (#PCDATA)>
		<!ELEMENT fanart11 (#PCDATA)>
		<!ELEMENT fanart12 (#PCDATA)>
		<!ELEMENT fanart13 (#PCDATA)>
		<!ELEMENT fanart14 (#PCDATA)>
		<!ELEMENT fanart15 (#PCDATA)>
		<!ELEMENT fanart16 (#PCDATA)>
		<!ELEMENT fanart17 (#PCDATA)>
		<!ELEMENT fanart18 (#PCDATA)>
		<!ELEMENT fanart19 (#PCDATA)>
		<!ELEMENT fanart20 (#PCDATA)>
		<!ELEMENT fanart21 (#PCDATA)>
		<!ELEMENT fanart22 (#PCDATA)>
		<!ELEMENT fanart23 (#PCDATA)>
		<!ELEMENT fanart24 (#PCDATA)>
		<!ELEMENT fanart25 (#PCDATA)>
		<!ELEMENT fanart26 (#PCDATA)>
		<!ELEMENT fanart27 (#PCDATA)>
		<!ELEMENT fanart28 (#PCDATA)>
		<!ELEMENT fanart29 (#PCDATA)>
		<!ELEMENT fanart30 (#PCDATA)>
		<!ELEMENT banner1 (#PCDATA)>
		<!ELEMENT banner2 (#PCDATA)>
		<!ELEMENT banner3 (#PCDATA)>
		<!ELEMENT banner4 (#PCDATA)>
		<!ELEMENT banner5 (#PCDATA)>
		<!ELEMENT banner6 (#PCDATA)>
		<!ELEMENT banner7 (#PCDATA)>
		<!ELEMENT banner8 (#PCDATA)>
		<!ELEMENT banner9 (#PCDATA)>
		<!ELEMENT banner10 (#PCDATA)>
		<!ELEMENT clearlogo1 (#PCDATA)>
		<!ELEMENT clearlogo2 (#PCDATA)>
		<!ELEMENT clearlogo3 (#PCDATA)>
		<!ELEMENT clearlogo4 (#PCDATA)>
		<!ELEMENT clearlogo5 (#PCDATA)>
		<!ELEMENT clearlogo6 (#PCDATA)>
		<!ELEMENT clearlogo7 (#PCDATA)>
		<!ELEMENT clearlogo8 (#PCDATA)>
		<!ELEMENT clearlogo9 (#PCDATA)>
		<!ELEMENT clearlogo10 (#PCDATA)>
]>
<datafile>
	<header>
		<emu_name>Dinothawr</emu_name>
		<emu_parser>NoIntro_parser.xml</emu_parser>
		<emu_description>Dinothawr</emu_description>
		<emu_category>ports</emu_category>
		<emu_version>20151220</emu_version>
		<emu_date>16/08/2016</emu_date>
		<emu_author>Lefty420</emu_author>
		<emu_homepage>http://www.no-intro.org</emu_homepage>
		<emu_baseurl>https://archive.org/download/</emu_baseurl>
		<emu_launcher>external</emu_launcher>
		<emu_ext_launch_cmd>none</emu_ext_launch_cmd>
		<emu_downloadpath>default</emu_downloadpath>
		<emu_postdlaction>unzip_update_rom_path_dosbox</emu_postdlaction>
		<emu_comment>Dinothawr Retroarch port, provided by Lefty420.</emu_comment>
			<emu_thumb>https://camo.githubusercontent.com/5b90c0cf264eef33ecd7623b9dd4b21f9f8f8f42/687474703a2f2f77696b692e6c6962726574726f2e636f6d2f696d616765732f322f32352f44696e6f74686177725469746c6553637265656e2e706e67</emu_thumb>
			<emu_banner>https://rpigame.files.wordpress.com/2016/02/dinothawr.png?w=920</emu_banner>
			<emu_fanart>https://lh5.ggpht.com/Mw3S3ekvWv02glYgP8fMNi0lRmSYXupsYuNemY5hmo10qyOvDwXMkYD2wf5hrhr4Yx4=h900</emu_fanart>
			<emu_logo>https://rpigame.files.wordpress.com/2016/02/dinothawr.png</emu_logo>
			<emu_trailer>VQpHejqlzzY</emu_trailer>
		</header>
			<game name="Dinothawr">
				<description>Dinothawr</description>
				<rom name="tom_bftp_D/dinothawr.zip" size="6728842" />
				<title_clean>Dinothawr</title_clean>
				<plot>Dinothawr is a block pushing puzzle game on slippery surfaces. Our hero is a dinosaur whose friends are trapped in ice. Through puzzles it is your task to free the dinos from their ice prison.</plot>
				<releasedate>21/09/2013</releasedate>
				<year>2013</year>
				<genre>Retro</genre>
				<nplayers>1</nplayers>
				<thegamesdb_id></thegamesdb_id>
				<videoid>d62cb9z6j9M</videoid>
				<giantbomb_url>http://www.giantbomb.com/dinothawr/3030-45105/</giantbomb_url>
				<boxart1>https://s-media-cache-ak0.pinimg.com/236x/87/f3/c6/87f3c6298d7377c6fc835b3582c32816.jpg</boxart1>
				<banner1>https://rpigame.files.wordpress.com/2016/02/dinothawr.png</banner1>
				<emu_command>dinothawr.game</emu_command>
			</game>
</datafile>
